"""
api.py
------
Flask REST API that serves Data Warehouse analytics data to the React frontend.
Endpoints return JSON data from PostgreSQL star schema AND snowflake schema queries.

Endpoints:
    ── Star Schema ──
    GET /api/schema              → Star schema table info (columns, row counts)
    GET /api/etl-log             → ETL pipeline log contents
    GET /api/sample/<table>      → First 10 rows of a star schema table
    GET /api/sales-by-country    → Total sales aggregated by country
    GET /api/top-products        → Top 5 products by revenue
    GET /api/monthly-revenue     → Monthly revenue trend
    GET /api/top-customers       → Top 10 customers by spending
    GET /api/quarterly-category  → Quarterly revenue by product category

    ── Snowflake Schema ──
    GET /api/snowflake-schema    → Snowflake schema table info (columns, row counts)
    GET /api/snowflake-sample/<table> → First 10 rows of a snowflake table
    GET /api/snowflake-sales-by-country   → Sales by country (using normalized tables)
    GET /api/snowflake-top-products       → Top products (using normalized tables)
    GET /api/snowflake-comparison         → Star vs Snowflake comparison data

Usage:
    python3 api.py
"""

from flask import Flask, jsonify
from flask_cors import CORS
from sqlalchemy import create_engine, text
from config import DATABASE_URL

app = Flask(__name__)
CORS(app)

engine = create_engine(DATABASE_URL, echo=False)


def query_to_list(sql: str) -> list[dict]:
    """Execute SQL and return list of dicts."""
    with engine.connect() as conn:
        result = conn.execute(text(sql))
        columns = list(result.keys())
        return [dict(zip(columns, row)) for row in result.fetchall()]


# ══════════════════════════════════════════════════════════════════════════════
# STAR SCHEMA ENDPOINTS
# ══════════════════════════════════════════════════════════════════════════════

# ── Schema Info ────────────────────────────────────────────────────────────────

@app.route("/api/schema")
def get_schema():
    """
    Return star schema table info (columns, row counts).

    This endpoint queries PostgreSQL's information_schema to get the column
    definitions for each star schema table, along with the row count.
    The frontend uses this to display table structure in the Schema tab.
    """
    tables = {}
    for table in ["dim_customers", "dim_products", "dim_date", "fact_sales"]:
        cols = query_to_list(f"""
            SELECT column_name, data_type
            FROM information_schema.columns
            WHERE table_name = '{table}'
            ORDER BY ordinal_position
        """)
        count = query_to_list(f"SELECT COUNT(*) as count FROM {table}")[0]["count"]
        tables[table] = {"columns": cols, "row_count": count}
    return jsonify(tables)


# ── ETL Log ────────────────────────────────────────────────────────────────────

@app.route("/api/etl-log")
def get_etl_log():
    """
    Return ETL pipeline log contents.

    Reads the etl.log file generated by etl_pipeline.py during the last run.
    Each line of the log shows a step in the ETL process (extract, transform, load).
    """
    try:
        with open("etl.log", "r") as f:
            lines = f.readlines()
        return jsonify({"log": [line.strip() for line in lines if line.strip()]})
    except FileNotFoundError:
        return jsonify({"log": ["ETL log not found. Run etl_pipeline.py first."]})


# ── Sample Data ────────────────────────────────────────────────────────────────

@app.route("/api/sample/<table_name>")
def get_sample(table_name):
    """
    Return first 10 rows of a star schema table.

    This is used by the Data Explorer tab to show students what the actual
    data looks like in each table. The table_name parameter is validated
    against an allowlist to prevent SQL injection.
    """
    allowed = ["dim_customers", "dim_products", "dim_date", "fact_sales"]
    if table_name not in allowed:
        return jsonify({"error": "Invalid table name"}), 400
    rows = query_to_list(f"SELECT * FROM {table_name} LIMIT 10")
    # Convert date objects to strings
    for row in rows:
        for k, v in row.items():
            if hasattr(v, "isoformat"):
                row[k] = v.isoformat()
    return jsonify(rows)


# ── Analytics Queries ──────────────────────────────────────────────────────────

@app.route("/api/sales-by-country")
def sales_by_country():
    """
    Total sales aggregated by country.

    SQL Explanation:
    - JOIN fact_sales with dim_customers on customer_id
    - GROUP BY country to aggregate per-country totals
    - COUNT orders, SUM quantities, SUM revenue
    - ORDER BY revenue DESC to show top countries first
    """
    data = query_to_list("""
        SELECT
            c.country,
            COUNT(f.order_id)::int AS total_orders,
            SUM(f.quantity)::int AS total_units_sold,
            ROUND(SUM(f.total_amount)::numeric, 2)::float AS total_revenue
        FROM fact_sales f
        JOIN dim_customers c ON f.customer_id = c.customer_id
        GROUP BY c.country
        ORDER BY total_revenue DESC
    """)
    return jsonify(data)


@app.route("/api/top-products")
def top_products():
    """
    Top 5 products by revenue.

    SQL Explanation:
    - JOIN fact_sales with dim_products on product_id
    - GROUP BY product_name and category
    - SUM total_amount for revenue, COUNT for order frequency
    - LIMIT 5 to get only top performers
    """
    data = query_to_list("""
        SELECT
            p.product_name,
            p.category,
            COUNT(f.order_id)::int AS times_ordered,
            SUM(f.quantity)::int AS total_units_sold,
            ROUND(SUM(f.total_amount)::numeric, 2)::float AS total_revenue
        FROM fact_sales f
        JOIN dim_products p ON f.product_id = p.product_id
        GROUP BY p.product_name, p.category
        ORDER BY total_revenue DESC
        LIMIT 5
    """)
    return jsonify(data)


@app.route("/api/monthly-revenue")
def monthly_revenue():
    """
    Monthly revenue trend.

    SQL Explanation:
    - JOIN fact_sales with dim_date on date_id
    - GROUP BY year and month for time-based aggregation
    - Creates a readable "Jan 2024" label for chart display
    """
    data = query_to_list("""
        SELECT
            d.year::int AS year,
            d.month::int AS month,
            COUNT(f.order_id)::int AS total_orders,
            ROUND(SUM(f.total_amount)::numeric, 2)::float AS monthly_revenue
        FROM fact_sales f
        JOIN dim_date d ON f.date_id = d.date_id
        GROUP BY d.year, d.month
        ORDER BY d.year, d.month
    """)
    # Create readable label
    month_names = ["", "Jan", "Feb", "Mar", "Apr", "May", "Jun",
                   "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
    for row in data:
        row["label"] = f"{month_names[row['month']]} {row['year']}"
    return jsonify(data)


@app.route("/api/top-customers")
def top_customers():
    """
    Top 10 customers by spending.

    SQL Explanation:
    - JOIN fact_sales with dim_customers to get customer details
    - GROUP BY customer fields to aggregate per-customer totals
    - ORDER BY total_spent DESC, LIMIT 10 for top spenders
    """
    data = query_to_list("""
        SELECT
            c.customer_id::int AS customer_id,
            c.customer_name,
            c.country,
            COUNT(f.order_id)::int AS total_orders,
            ROUND(SUM(f.total_amount)::numeric, 2)::float AS total_spent
        FROM fact_sales f
        JOIN dim_customers c ON f.customer_id = c.customer_id
        GROUP BY c.customer_id, c.customer_name, c.country
        ORDER BY total_spent DESC
        LIMIT 10
    """)
    return jsonify(data)


@app.route("/api/quarterly-category")
def quarterly_category():
    """
    Quarterly revenue by product category.

    SQL Explanation:
    - JOIN fact_sales with both dim_date AND dim_products
    - GROUP BY year, quarter, and category for multi-dimensional analysis
    - This demonstrates how fact tables connect to multiple dimensions
    """
    data = query_to_list("""
        SELECT
            d.year::int AS year,
            d.quarter::int AS quarter,
            p.category,
            ROUND(SUM(f.total_amount)::numeric, 2)::float AS quarterly_revenue
        FROM fact_sales f
        JOIN dim_date d ON f.date_id = d.date_id
        JOIN dim_products p ON f.product_id = p.product_id
        GROUP BY d.year, d.quarter, p.category
        ORDER BY d.year, d.quarter, quarterly_revenue DESC
    """)
    return jsonify(data)


# ══════════════════════════════════════════════════════════════════════════════
# SNOWFLAKE SCHEMA ENDPOINTS
# ══════════════════════════════════════════════════════════════════════════════
# The snowflake schema normalizes dimension tables further.
# For example, instead of storing "Electronics" as a string in dim_products,
# the snowflake version stores a category_id that references dim_categories.
#
# Key difference from star schema:
#   Star:      fact_sales → dim_products (has category string)
#   Snowflake: fact_sales_sf → dim_products_sf → dim_categories (category in separate table)
#
# This means snowflake queries need MORE JOINs but have LESS data redundancy.
# ══════════════════════════════════════════════════════════════════════════════

@app.route("/api/snowflake-schema")
def get_snowflake_schema():
    """
    Return snowflake schema table info (columns, row counts).

    Similar to /api/schema but for snowflake tables.
    Notice how dim_products_sf has category_id (FK) instead of category (string),
    and dim_customers_sf has country_id (FK) instead of country (string).
    The sub-dimension tables (dim_categories, dim_countries) hold the actual values.
    """
    tables = {}
    sf_tables = [
        "dim_categories",      # Sub-dimension: product categories
        "dim_countries",       # Sub-dimension: customer countries
        "dim_products_sf",     # Normalized dimension (uses category_id FK)
        "dim_customers_sf",    # Normalized dimension (uses country_id FK)
        "dim_date",            # Shared with star schema (already normalized)
        "fact_sales_sf",       # Fact table (same structure as star)
    ]
    for table in sf_tables:
        cols = query_to_list(f"""
            SELECT column_name, data_type
            FROM information_schema.columns
            WHERE table_name = '{table}'
            ORDER BY ordinal_position
        """)
        count = query_to_list(f"SELECT COUNT(*) as count FROM {table}")[0]["count"]
        tables[table] = {"columns": cols, "row_count": count}
    return jsonify(tables)


@app.route("/api/snowflake-sample/<table_name>")
def get_snowflake_sample(table_name):
    """
    Return first 10 rows of a snowflake schema table.

    For sub-dimension tables (dim_categories, dim_countries), this shows the
    lookup values extracted from the original star schema dimensions.
    For dim_products_sf and dim_customers_sf, you can see the FK references
    instead of the full string values.
    """
    allowed = [
        "dim_categories", "dim_countries",
        "dim_products_sf", "dim_customers_sf",
        "dim_date", "fact_sales_sf",
    ]
    if table_name not in allowed:
        return jsonify({"error": "Invalid table name"}), 400
    rows = query_to_list(f"SELECT * FROM {table_name} LIMIT 10")
    # Convert date objects to strings
    for row in rows:
        for k, v in row.items():
            if hasattr(v, "isoformat"):
                row[k] = v.isoformat()
    return jsonify(rows)


@app.route("/api/snowflake-sales-by-country")
def snowflake_sales_by_country():
    """
    Total sales by country using SNOWFLAKE schema tables.

    SQL Explanation (notice the extra JOIN compared to star schema):
    - Star Schema:      fact_sales → dim_customers (country is in dim_customers)
    - Snowflake Schema: fact_sales_sf → dim_customers_sf → dim_countries

    The snowflake version needs an EXTRA JOIN because the country name is
    stored in a separate dim_countries table (normalized), while in star schema
    it's stored directly in dim_customers (denormalized).

    This is the key trade-off:
    - Star: Fewer JOINs = faster queries, but country is duplicated across customers
    - Snowflake: More JOINs = slightly slower, but country is stored only once
    """
    data = query_to_list("""
        SELECT
            co.country_name AS country,
            COUNT(f.order_id)::int AS total_orders,
            SUM(f.quantity)::int AS total_units_sold,
            ROUND(SUM(f.total_amount)::numeric, 2)::float AS total_revenue
        FROM fact_sales_sf f
        JOIN dim_customers_sf c ON f.customer_id = c.customer_id
        JOIN dim_countries co ON c.country_id = co.country_id
        GROUP BY co.country_name
        ORDER BY total_revenue DESC
    """)
    return jsonify(data)


@app.route("/api/snowflake-top-products")
def snowflake_top_products():
    """
    Top 5 products by revenue using SNOWFLAKE schema tables.

    SQL Explanation (notice the extra JOIN compared to star schema):
    - Star Schema:      fact_sales → dim_products (category is in dim_products)
    - Snowflake Schema: fact_sales_sf → dim_products_sf → dim_categories

    To get the category NAME in snowflake, we must join through dim_products_sf
    to dim_categories, because dim_products_sf only stores category_id.
    """
    data = query_to_list("""
        SELECT
            p.product_name,
            cat.category_name AS category,
            COUNT(f.order_id)::int AS times_ordered,
            SUM(f.quantity)::int AS total_units_sold,
            ROUND(SUM(f.total_amount)::numeric, 2)::float AS total_revenue
        FROM fact_sales_sf f
        JOIN dim_products_sf p ON f.product_id = p.product_id
        JOIN dim_categories cat ON p.category_id = cat.category_id
        GROUP BY p.product_name, cat.category_name
        ORDER BY total_revenue DESC
        LIMIT 5
    """)
    return jsonify(data)


@app.route("/api/snowflake-comparison")
def snowflake_comparison():
    """
    Return comparison data between Star and Snowflake schemas.

    This endpoint provides side-by-side metrics so students can understand
    the structural differences:
    - Table counts (star has 4 tables, snowflake has 6)
    - Total columns across all tables
    - Number of JOINs needed for common queries
    - Storage characteristics

    Educational Note:
    Both schemas produce IDENTICAL analytical results. The difference is
    in how the data is organized (normalized vs denormalized) and the
    implications for query complexity and storage efficiency.
    """
    # Star schema metrics
    star_tables = ["dim_customers", "dim_products", "dim_date", "fact_sales"]
    star_info = {}
    total_star_cols = 0
    total_star_rows = 0
    for t in star_tables:
        cols = query_to_list(f"""
            SELECT COUNT(*) as count FROM information_schema.columns
            WHERE table_name = '{t}'
        """)[0]["count"]
        rows = query_to_list(f"SELECT COUNT(*) as count FROM {t}")[0]["count"]
        star_info[t] = {"columns": cols, "rows": rows}
        total_star_cols += cols
        total_star_rows += rows

    # Snowflake schema metrics
    sf_tables = ["dim_categories", "dim_countries", "dim_products_sf",
                 "dim_customers_sf", "dim_date", "fact_sales_sf"]
    sf_info = {}
    total_sf_cols = 0
    total_sf_rows = 0
    for t in sf_tables:
        cols = query_to_list(f"""
            SELECT COUNT(*) as count FROM information_schema.columns
            WHERE table_name = '{t}'
        """)[0]["count"]
        rows = query_to_list(f"SELECT COUNT(*) as count FROM {t}")[0]["count"]
        sf_info[t] = {"columns": cols, "rows": rows}
        total_sf_cols += cols
        total_sf_rows += rows

    return jsonify({
        "star": {
            "tables": star_info,
            "total_tables": len(star_tables),
            "total_columns": total_star_cols,
            "total_rows": total_star_rows,
            "joins_for_country_query": 1,    # fact → dim_customers
            "joins_for_product_query": 1,    # fact → dim_products
        },
        "snowflake": {
            "tables": sf_info,
            "total_tables": len(sf_tables),
            "total_columns": total_sf_cols,
            "total_rows": total_sf_rows,
            "joins_for_country_query": 2,    # fact → dim_customers_sf → dim_countries
            "joins_for_product_query": 2,    # fact → dim_products_sf → dim_categories
        },
    })


if __name__ == "__main__":
    print("🚀 API running at http://localhost:5001")
    app.run(host="0.0.0.0", port=5001, debug=True)
